# Generated by Django 2.2.19 on 2023-07-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterprise',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.Division', verbose_name='Дивизион'),
        ),
        migrations.AlterField(
            model_name='question',
            name='enterprise',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='questions.Enterprise', verbose_name='Предприятие'),
        ),
    ]
